# Generated by Django 3.2.9 on 2023-12-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20231229_2022'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
