# Generated by Django 3.2.9 on 2023-12-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('applicants', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ManyToManyField(to='applicants.Candidate'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
