# Generated by Django 3.2.9 on 2023-12-29 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20231229_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('image', models.FileField(null=True, upload_to='employer/images')),
                ('gender', models.CharField(max_length=15, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('company', models.CharField(max_length=25, null=True)),
                ('status', models.CharField(max_length=25, null=True)),
                ('position', models.CharField(max_length=25, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('image', models.FileField(null=True, upload_to='candidate/images')),
                ('education', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('skill', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField()),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ManyToManyField(to='job.Candidate'),
        ),
    ]
